services:
  todo-database:
    image: mongo:4.4
    container_name: todo-database
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - todo-volume:/data/db
    networks:
      - todo-net

  todo-server:
    build:
      context: ./todo-src
      dockerfile: Dockerfile
    image: todo-server
    container_name: todo-server
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - ./todo-src/.env
    depends_on:
      - todo-database
    networks:
      - todo-net

volumes:
  todo-volume:

networks:
  todo-net:
    driver: bridge

