apiVersion: v1
kind: Service
metadata:
  name: todo-server
  labels:
    app: todo-server
spec:
  type: NodePort
  selector:
    app: todo-server
  ports:
  - protocol: TCP
    port: 80       # External Port
    targetPort: 3000  # Internal Port
    nodePort: 30080   # NodePort (direct access)

